# Generated by Django 4.1.7 on 2023-03-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='description',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='gender',
        ),
    ]
