# Generated by Django 4.1.7 on 2023-03-21 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_purchase_user_purchaseitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='base.item'),
        ),
    ]
