# Generated by Django 4.1.7 on 2023-03-21 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_item_purchases_purchase_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aa', to='base.item'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bb', to='base.purchase'),
        ),
    ]
