# Generated by Django 4.1.7 on 2023-03-27 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_purchase_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_products', models.IntegerField()),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=5)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_products', models.IntegerField()),
                ('price', models.IntegerField()),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.basket')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='items',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='purchase',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='noOrders',
            new_name='number_orders',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phoneNo',
            new_name='phone_number',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='PurchaseItem',
        ),
        migrations.AddField(
            model_name='product',
            name='baskets',
            field=models.ManyToManyField(through='base.ProductBasket', to='base.basket'),
        ),
        migrations.AddField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(through='base.ProductBasket', to='base.product'),
        ),
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='base.user'),
        ),
    ]
