# Generated by Django 4.1.7 on 2023-03-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_basket_product_productbasket_remove_purchase_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='date',
            field=models.DateField(),
        ),
    ]
