# Generated by Django 4.1.7 on 2023-03-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_basket_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='number_orders',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='-empty-', max_length=100),
        ),
    ]
