# Generated by Django 4.1.7 on 2023-03-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_user_number_orders_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='number_products',
        ),
        migrations.AlterField(
            model_name='basket',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
