# Generated by Django 4.1.7 on 2023-03-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_basket_number_products_alter_basket_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbasket',
            name='number_products',
        ),
    ]
