# Generated by Django 4.1.7 on 2023-03-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_productbasket_number_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productbasket',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
