# Generated by Django 4.1.7 on 2023-03-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_basket_discount_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbasket',
            name='number_products',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='basket',
            name='date',
            field=models.DateField(),
        ),
    ]
