# Generated by Django 4.1.7 on 2023-03-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_productbasket_number_products_alter_basket_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='number_products',
            field=models.IntegerField(default=0),
        ),
    ]
