# Generated by Django 4.1.7 on 2023-03-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_basket_number_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='discount',
        ),
        migrations.AddField(
            model_name='basket',
            name='discount_code',
            field=models.CharField(default='-no discount-', max_length=25),
        ),
    ]
